enum COMMON_ERROR_CODES {
  INVALID_REQUEST = "INVALID_PARAMETER",
  FORBIDDEN = "FORBIDDEN",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

export { COMMON_ERROR_CODES };
